### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by Imchrisrivers** [digital-asset/ex-cdm-swaps#30]
Application crashes when executing the Docker commands. This occurs even after increasing to 4 CPUs and 8 GB RAM. Others have had success with increasing to 16 GB RAM, but that’s their hardware limit.

**Comment by tweber-da** [comment]
The docker commands were updated with https://github.com/digital-asset/ex-cdm-swaps/pull/32. This should run on a 16 GB RAM setup and the README was updated accordingly. For now we won't try to make it less resource intensive.

**Comment by tweber-da** [comment]
The docker commands were updated with https://github.com/digital-asset/ex-cdm-swaps/pull/32. This should run on a 16 GB RAM setup and the README was updated accordingly. For now we won't try to make it less resource intensive.
